version: '3'
services:
  mysql:
    image: docker.io/mysql:5.5
    environment:
    - MYSQL_DATABASE=nandy
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 3306:3306
  dump:
    build: .
    command: mysql/dump.sh
    depends_on:
    - mysql
    volumes:
    - ./lib:/opt/pi-k8s/lib
    - ./mysql:/opt/pi-k8s/mysql
    - ./test:/opt/pi-k8s/test
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - GRAPHITE_HOST=graphite
    - GRAPHITE_PORT=2003
